name: Puppy Linux Kernel Build + AUFS

on:
  # schedule:
  # - cron: '0 2 */20 * *' # daily at 02:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: debian:sid

    env:
      BASE_VERSION: "7.1"
      CUSTOM_VERSION: "opkm"
      TARGET_CPU_ARCH: "x86"
      
      AUFS_REPO: "https://github.com/sfjro/aufs-standalone.git"
      AUFS_BRANCH: "aufs7.1"  # Replace with desired AUFS branch
      AUFS_PATCH_FILES: "aufs7-kbuild.patch aufs7-base.patch aufs7-mmap.patch aufs7-standalone.patch"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          apt-get update
          apt-get install -y \
            build-essential bc bison flex libssl-dev libelf-dev dwarves pahole \
            squashfs-tools wget xz-utils ca-certificates gcc g++ binutils \
            llvm clang kmod python3 curl git jq patch rsync

      - name: Detect latest kernel patch
        id: detect_kernel
        run: |
          set -euo pipefail

          echo "Checking kernel.org releases for base ${BASE_VERSION}..."
          releases_json="$(curl -sS https://www.kernel.org/releases.json)"

          LATEST=$(printf '%s\n' "$releases_json" \
            | jq -r --arg base "${BASE_VERSION}." '.releases[]
                | select(.version | startswith($base))
                | .version' \
            | sort -V \
            | tail -n 1)

          if [ -z "$LATEST" ]; then
            echo "No patch found. Using base ${BASE_VERSION}"
            echo "KERNEL_VERSION=$BASE_VERSION" >> $GITHUB_ENV
          else
            echo "Detected latest kernel patch: $LATEST"
            echo "KERNEL_VERSION=$LATEST" >> $GITHUB_ENV
          fi

          
      - name: Download Linux kernel
        run: |
          wget https://cdn.kernel.org/pub/linux/kernel/v${BASE_VERSION%%.*}.x/linux-$KERNEL_VERSION.tar.xz
          tar -xf linux-$KERNEL_VERSION.tar.xz
          mv linux-$KERNEL_VERSION linux

      - name: Clone AUFS repository
        run: git clone --depth=1 --branch $AUFS_BRANCH $AUFS_REPO aufs

      - name: Apply AUFS patches
        run: |
          set -e
          cd linux
          PATCH_DIR="../aufs"
          cp -rf $PATCH_DIR/fs ./ 
          cp -rf $PATCH_DIR/Documentation ./
          cp -f $PATCH_DIR/include/uapi/linux/aufs_type.h include/linux/
          cp -rf $PATCH_DIR/include ./
          for patch in $AUFS_PATCH_FILES ; do
            if [ -f "$PATCH_DIR/$patch" ]; then
              echo "Applying patch $PATCH_DIR/$patch..."
              patch -p1 < "$PATCH_DIR/$patch" || echo "Patch $patch failed, skipping"
            fi
          done

      - name: Set custom version string
        working-directory: linux
        run: echo "${CUSTOM_VERSION}" > .config.localversion

      - name: Export KMOD_VERSION
        run: echo "KMOD_VERSION=$KERNEL_VERSION-$(cat linux/.config.localversion)" >> $GITHUB_ENV       

      - name: Copy provided .config
        run: |
              sed -i -e "s#^EXTRAVERSION\ =.*#EXTRAVERSION=-$CUSTOM_VERSION#" linux/Makefile
              cp .config-aufs linux/.config

      - name: Auto-update config
        working-directory: linux
        run: |
              make olddefconfig
              cp -f .config kernel-${KMOD_VERSION}-aufs.config

      - name: Upload kernel config
        uses: actions/upload-artifact@v4
        with:
          name: kernel-${{ env.KMOD_VERSION }}-aufs-config
          path: |
                linux/kernel-${{ env.KMOD_VERSION }}-aufs.config              
          
      - name: Build kernel image
        working-directory: linux
        run: make -j"$(nproc)" bzImage
        
      - name: Build modules
        working-directory: linux
        run: | 
             make modules -j"$(nproc)"

      - name: Install modules into staging
        working-directory: linux
        run: |
          mkdir -p ../staging
          make modules_install INSTALL_MOD_PATH=../staging

      - name: Strip unneeded symbols
        run: find staging/lib/modules -type f -name '*.ko' -exec strip --strip-unneeded {} \;

      - name: Prepare DKMS kernel build tree
        working-directory: linux
        run: |

          CPU_ARCH=$TARGET_CPU_ARCH
          
          mkdir -p ../dkms-header-staging/build

          # IMPORTANT: ensure build tree is ready for external modules
          make prepare
          make modules_prepare
          make scripts
          make tools/objtool

          # Copy full minimal build tree required by DKMS
          cp -arf \
            include \
            Module.symvers \
            Makefile \
            Kconfig \
            .config \
            ../dkms-header-staging/build

          mkdir -p ../dkms-header-staging/build/arch
          cp -arf arch/$CPU_ARCH ../dkms-header-staging/build/arch/

          # required symlink for kernel module system
          ln -sr ../dkms-header-staging/build ../dkms-header-staging/source
          
          for dir1 in configs hyperv ia32 lib net power purgatory ras video mfd
          do
            find ../dkms-header-staging/build/arch/$CPU_ARCH -type d -name "$dir1" | xargs -i rm -rf {}
          done
          
          find ../dkms-header-staging/ -type f -name "*.c" | xargs -i rm -f {}
          find ../dkms-header-staging/ -type f -name "*.d" | xargs -i rm -f {}
          find ../dkms-header-staging/ -type f -name "*.o" | xargs -i rm -f {}
          find ../dkms-header-staging/ -type f -name "*.ko" | xargs -i rm -f {}
          find ../dkms-header-staging/ -type f -name "*.a" | xargs -i rm -f {}
          find ../dkms-header-staging/ -type f -name "*.S" | xargs -i rm -f {}
          find ../dkms-header-staging/ -type f -name "*.tmp" | xargs -i rm -f {}
          find ../dkms-header-staging/ -type f -name "*.obj" | xargs -i rm -f {}
          find ../dkms-header-staging/ -type f -name "*.elf" | xargs -i rm -f {}
          find ../dkms-header-staging/ -type f -name "*.cmd" | xargs -i rm -f {}
          find ../dkms-header-staging/ -type f -name "*.bin" | xargs -i rm -f {} 
          find ../dkms-header-staging/ -type f -name "*.debug" | xargs -i rm -f {}  
          find ../dkms-header-staging/ -type f -name "*.xz" | xargs -i rm -f {}  
          find ../dkms-header-staging/ -type f -name "vmlinux" | xargs -i rm -f {}
          find ../dkms-header-staging/ -type f -name "vmlinux.*" | xargs -i rm -f {}
          find ../dkms-header-staging/ -type f -name "bzImage" | xargs -i rm -f {}

          cp -arf scripts ../dkms-header-staging/build/
          
          mkdir -p ../dkms-header-staging/build/tools
          cp -arf tools/objtool ../dkms-header-staging/build/tools/

          for dir2 in atomic bash-completion clang-tools coccinelle crypto dummy-tools gdb ipe ksymoops livepatch package selinux tracing
          do
            find ../dkms-header-staging/build/scripts -type d -name "$dir2" | xargs -i rm -rf {}
          done          

          find ../dkms-header-staging/ -type f -name "*.o" | xargs -i rm -f {}
          find ../dkms-header-staging/ -type f -name "*.cmd" | xargs -i rm -f {}
          find ../dkms-header-staging/ -type f -name "*.tmp" | xargs -i rm -f {}
          find ../dkms-header-staging/build/tools/ -type f -name "*.a" | xargs -i rm -f {}
          
          find ../dkms-header-staging/ -type f -name ".gitignore" | xargs -i rm -f {}

      - name: Install kernel headers
        working-directory: linux
        run: |
          mkdir -p ../kernel-headers
          make headers_install INSTALL_HDR_PATH=../kernel-headers

      - name: Prepare SquashFS root
        run: |
          mkdir -p squashfs-root/lib/modules
          mkdir -p squashfs-root-usrmerge/usr/lib/modules
          
          mkdir -p kernel-dkms/lib/modules/${KMOD_VERSION}
          mkdir -p kernel-dkms-usrmerge/usr/lib/modules/${KMOD_VERSION}
         
          cp -arf staging/lib/modules/* squashfs-root/lib/modules/          
          cp -arf staging/lib/modules/* squashfs-root-usrmerge/usr/lib/modules/

          for mdir in squashfs-root/lib/modules squashfs-root-usrmerge/usr/lib/modules
          do
             find ./$mdir -maxdepth 2 -type l -name "build" -exec rm -f {} \;
          done

          mkdir -p squashfs-root/usr/include
          mkdir -p squashfs-root-usrmerge/usr/include

          cp -arf kernel-headers/include/* squashfs-root/usr/include/
          cp -arf kernel-headers/include/* squashfs-root-usrmerge/usr/include/
          
          mkdir -p kernel-headers-squashfs/usr/include
          cp -a kernel-headers/include/* kernel-headers-squashfs/usr/include/ 
          
          cp linux/arch/x86/boot/bzImage ./vmlinuz
          cp -f linux/.config kernel-${KMOD_VERSION}.config
              
          cp -arf dkms-header-staging/* squashfs-root/lib/modules/${KMOD_VERSION}/
          cp -arf dkms-header-staging/* squashfs-root-usrmerge/usr/lib/modules/${KMOD_VERSION}/
          
          cp -arf dkms-header-staging/* kernel-dkms/lib/modules/${KMOD_VERSION}/
          cp -arf dkms-header-staging/* kernel-dkms-usrmerge/usr/lib/modules/${KMOD_VERSION}/
          
      - name: Create Kernel Modules SquashFS
        run: |
          mksquashfs squashfs-root huge-kernel-${KMOD_VERSION}-aufs.sfs \
            -comp xz -Xdict-size 100% -b 1M -noappend -Xbcj x86
          mksquashfs squashfs-root-usrmerge huge-kernel-${KMOD_VERSION}-aufs-usrmerge.sfs \
            -comp xz -Xdict-size 100% -b 1M -noappend -Xbcj x86

      - name: Create Kernel Userspace Headers SquashFS
        run: |
          mksquashfs kernel-headers-squashfs \
            kernel-userspace-headers-${KMOD_VERSION}-aufs.sfs \
            -comp xz -Xdict-size 100% -b 1M -noappend -Xbcj x86

      - name: Create Kernel DKMS Headers SquashFS
        run: |
          mksquashfs kernel-dkms \
            kernel-dkms-headers-${KMOD_VERSION}-aufs.sfs \
            -comp xz -Xdict-size 100% -b 1M -noappend -Xbcj x86  
            
          mksquashfs kernel-dkms-usrmerge \
            kernel-dkms-headers-${KMOD_VERSION}-aufs-usrmerge.sfs \
            -comp xz -Xdict-size 100% -b 1M -noappend -Xbcj x86  

      - name: Upload kernel package (traditional)
        uses: actions/upload-artifact@v4
        with:
          name: huge-kernel-${{ env.KMOD_VERSION }}-aufs
          path: |
                 huge-kernel-${{ env.KMOD_VERSION }}-aufs.sfs
                 vmlinuz
                 
      - name: Upload kernel package (usrmerge)
        uses: actions/upload-artifact@v4
        with:
          name: huge-kernel-${{ env.KMOD_VERSION }}-aufs-usrmerge
          path: |
                 huge-kernel-${{ env.KMOD_VERSION }}-aufs-usrmerge.sfs
                 vmlinuz

      - name: Upload kernel userspace headers
        uses: actions/upload-artifact@v4
        with:
          name: kernel-userspace-headers-${{ env.KMOD_VERSION }}-aufs
          path: kernel-userspace-headers-${{ env.KMOD_VERSION }}-aufs.sfs

      - name: Upload DKMS kernel headers (traditional)
        uses: actions/upload-artifact@v4
        with:
          name: kernel-dkms-headers-${{ env.KMOD_VERSION }}-aufs
          path: kernel-dkms-headers-${{ env.KMOD_VERSION }}-aufs.sfs          

      - name: Upload DKMS kernel headers (usrmerge)
        uses: actions/upload-artifact@v4
        with:
          name: kernel-dkms-headers-${{ env.KMOD_VERSION }}-aufs-usrmerge
          path: kernel-dkms-headers-${{ env.KMOD_VERSION }}-aufs-usrmerge.sfs
